name: pMRI
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.8.4
  - numpy=1.26.4
  - scipy=1.13.1
  - pytorch=2.5.1
  - pywavelets=1.7.0
  - scikit-learn=1.5.2
  
 
